### PR TITLE
Update GraphQL to version 15.0.0

### PR DESCRIPTION
**Pull request by frikille**
This PR fixes the tests that are broken in #131.

The tests were broken because of changes in the error messages.

The Typescript check also failed because in the `node_modules/graphql-tools` package has two TS errors related to the schema stitching which is not used by this project at all. This can be avoided if the `IResolvers` type is not imported from the `graphql-tools` lib but included in the `types.d.ts` file.

### CODE REVIEW

**Comment by numToStr** [comment]
Any ETA when this going to be released?

**Comment by mcollina** [comment]
I’m waiting for a new version of graphql-jit. I’m also uncertain to ship this together with the support for fastify v3 or not.

wdyt?

**Comment by numToStr** [comment]
I guess, you know better than me ✌🏻. But, If fastify v3 support is not a breaking change than you can ship it in a minor version. Bcz most of the gql stuffs are already migrated to v15.

BTW thanks for giving us some of the most awesome libs for nodejs ♥️.

**Comment by mcollina** [comment]
Are there any new features you plan to use or some incompatibilities you know about this change?

**Comment by numToStr** [comment]
Nothing major. I am just using type-graphql w/ fastify-gql. And, type-graphql already released v1.rc w/ v15 support. So, I can't use that until fastify-gql gets v15 support.

**Pull request merged**
