### PR TITLE
Fix :: Gateway :: Slow test: test/gateway/pollingInterval.js

### LINKED ISSUE #237: Slow test: test/gateway/pollingInterval.js
This suitte is really slow: https://github.com/mcollina/fastify-gql/blob/master/test/gateway/pollingInterval.js takes up to 8 seconds on my machine. We should speed it up

cc @iviaks

### PR DESCRIPTION
**Pull request by iviaks**
Closes #237

### CODE REVIEW

**Comment by iviaks** [comment]
@mcollina 
Take a look at this line
https://github.com/mcollina/fastify-gql/pull/238/files#diff-0d5545bb9a2fea37f5d0112e8c4c7a72R522

Is it possible?

**Comment by iviaks** [comment]
Something wrong with CI / CD
I'm using [@sinonjs/fake-timers](https://www.npmjs.com/package/@sinonjs/fake-timers) library, but CI / CD can't install it

```log
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@sinonjs%2ffake-timers - Not found
npm ERR! 404 
npm ERR! 404  '@sinonjs/fake-timers@^6.0.1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'fastify-gql'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2020-08-06T09_27_48_914Z-debug.log
##[error]Process completed with exit code 1.
```

**Comment by mcollina** [comment]
npm is down.

**Comment by mcollina** [comment]
> Take a look at this line
https://github.com/mcollina/fastify-gql/pull/238/files#diff-0d5545bb9a2fea37f5d0112e8c4c7a72R522

> Is it possible?

I don't understand the question.

**Comment by iviaks** [comment]
I'm closing connection to user service (for reducing time of executing test). Connection will be refreshed on .refresh() call

**Comment by mcollina** [comment]
I still don't understand :(.

**Comment by iviaks** [comment]
@mcollina 
Yea, I was re-reading my previous message, and I will try to explain it in details :)

We had an issue with slow shutting down of newly created user-service.
It's because this service keeps a connection to Gateway (like a WebSocket connection).

I did a small fix for it (just inside a test). Now, before shutting down of user-service, we're closing the connection between User-Service and Gateway-Service. In this case, shutdown works much faster and tests are working faster.

If it's ok, we can make tests faster in this way.
If it's not ok, we have to find a solution, how to shutdown user-service without an additional timeout.

**Comment by mcollina** [comment]
This is ok

**Pull request merged**
